resolver: lts-14.27
# ghc-options:
#   ridley: -Wall -Werror
packages:
- '.'
extra-deps:
- ekg-core-0.1.1.7
- ekg-prometheus-adapter-0.1.0.4
- katip-0.7.0.0
- prometheus-2.1.3
- wai-middleware-metrics-0.2.4
