resolver: lts-12.18

packages:
- 'ridley'
- 'ridley-extras'

extra-deps:
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.0
  - katip-0.6.3.0

flags:
  ridley:
    lib-Werror: true

extra-package-dbs: []
