resolver: lts-12.18

packages:
- 'ridley'
- 'ridley-extras'

extra-deps:

  - git: git@github.com:kadena-io/ekg-prometheus-adapter.git
    commit: bd93dd5596d626b121f567bb24c0741fa0c8ccdd
  - prometheus-2.1.0
  - katip-0.6.3.0

flags:
  ridley:
    lib-Werror: true

extra-package-dbs: []
